#include "NBodyUtils.h"
#include <fstream>
#include "Engine/Engine.h"

static std::string GetLogFilePath()
{
	static const FString FilePath1 = FPaths::ProjectSavedDir() + TEXT("Logs/GraphSystem_Debug.log");
	static const std::string FilePath = TCHAR_TO_UTF8(*FilePath1);
	return FilePath;
}

void ClearLogFile()
{
	std::ofstream LogFile(GetLogFilePath().c_str(), std::ios::trunc);
	if (LogFile.is_open())
	{
		LogFile.close();
		UE_LOG(LogTemp, Log, TEXT("GraphSystem log file cleared successfully."));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("Failed to clear GraphSystem log file at: %s"), *FString(GetLogFilePath().c_str()));
	}
}

void LogAlways(const FString& TextToWrite)
{
	// Open/close each time for simplicity and hot-reload safety
	// Performance note: For high-frequency logging, consider batching or using a persistent handle
	
	// Ensure directory exists
	FString LogFilePathFString = FPaths::ProjectSavedDir() + TEXT("Logs/GraphSystem_Debug.log");
	FString LogDirectory = FPaths::GetPath(LogFilePathFString);
	
	if (!FPaths::DirectoryExists(LogDirectory))
	{
		IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
		if (!PlatformFile.CreateDirectoryTree(*LogDirectory))
		{
			UE_LOG(LogTemp, Error, TEXT("Failed to create log directory: %s"), *LogDirectory);
			return;
		}
	}
	
	std::string LogFilePath = TCHAR_TO_UTF8(*LogFilePathFString);
	std::ofstream LogFile(LogFilePath.c_str(), std::ios::app);
	if (LogFile.is_open())
	{
		LogFile << TCHAR_TO_ANSI(*TextToWrite) << std::endl;
		LogFile.close();
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("Failed to open GraphSystem log file for writing: %s"), *LogFilePathFString);
	}
}

void LogMessageInternal(const FString& StringToLog, bool LOG, int SeverityLevel, const FString& Prefix)
{
	if (!LOG || StringToLog.IsEmpty())
	{
		return;
	}
	
	FString LogMessage = Prefix + StringToLog;

	switch (SeverityLevel)
	{
	case 0:
		UE_LOG(LogTemp, Log, TEXT("%s"), *LogMessage);
		break;
	case 1:
		UE_LOG(LogTemp, Warning, TEXT("%s"), *LogMessage);
		break;
	case 2:
		UE_LOG(LogTemp, Error, TEXT("%s"), *LogMessage);
		break;
	default:
		UE_LOG(LogTemp, Log, TEXT("%s"), *LogMessage);
		break;
	}

	LogAlways(StringToLog);
}

FVector Jiggle(const FVector& Vec, float Magnitude)
{
	// Add small random perturbation to near-zero components to prevent division by zero
	// This is used in physics calculations when vectors become too small
	// Note: Implementation generated by Kiro, not from original d3-force library
	FVector Result = Vec;
	if (FMath::IsNearlyZero(Result.X))
	{
		Result.X = (FMath::FRand() - 0.5f) * Magnitude;
	}
	if (FMath::IsNearlyZero(Result.Y))
	{
		Result.Y = (FMath::FRand() - 0.5f) * Magnitude;
	}
	if (FMath::IsNearlyZero(Result.Z))
	{
		Result.Z = (FMath::FRand() - 0.5f) * Magnitude;
	}
	return Result;
}

void GraphSystemDebugBreak()
{
	// Debug helper for critical errors in graph system
	// Used as a breakpoint location during development to investigate issues
	UE_LOG(LogTemp, Error, TEXT("GraphSystem: Critical error - check call stack for details"));
}
